import type { Metadata } from "next";
import { Outfit, Lora } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/Header";
import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Top } from "@/components/top";
import { ThemeProvider } from "@/components/theme-provider";
import { OrganizationProvider } from "@/lib/contexts/OrganizationContext";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${lora.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <OrganizationProvider>
            <Header />
            <SidebarProvider>
              <div className="flex min-h-screen w-full">
                <AppSidebar />
                <div className="flex-1 min-w-0 flex flex-col w-full">
                  <main className="p-2 md:p-2 md:pl-2 bg-sidebar min-h-screen w-full">
                    <div className="rounded-xl overflow-hidden shadow-md border min-h-screen bg-background w-full">
                      
                      <div className="p-4 md:p-8 w-full">
                        {children}
                      </div>
                    </div>
                  </main>
                </div>
              </div>
            </SidebarProvider>
          </OrganizationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
