// Product type specific attribute configurations
// These define what attributes are available for each product type

export interface AttributeField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'multiselect' | 'boolean' | 'textarea' | 'toggle' | 'amenities';
  required?: boolean;
  options?: string[]; // For select/multiselect
  placeholder?: string;
  description?: string;
  validation?: {
    min?: number;
    max?: number;
    pattern?: string;
  };
}

export interface ProductTypeConfig {
  name: string;
  description: string;
  attributes: AttributeField[];
}

export const PRODUCT_TYPE_CONFIGS: Record<string, ProductTypeConfig> = {
  accommodation: {
    name: 'Accommodation',
    description: 'Hotels, resorts, apartments, and other lodging',
    attributes: [
      // Core Room Information
      {
        key: 'room_type',
        label: 'Room Type',
        type: 'select',
        required: true,
        options: [
          'Single Room',
          'Double Room', 
          'Twin Room',
          'Triple Room',
          'Family Room',
          'Suite',
          'Apartment',
          'Villa',
          'Studio'
        ]
      },
      {
        key: 'bed_config',
        label: 'Bed Configuration',
        type: 'select',
        required: true,
        options: [
          '1 Single Bed',
          '2 Single Beds',
          '1 Double Bed',
          '1 King Bed',
          '1 Queen Bed',
          '1 Single + 1 Sofa Bed',
          '2 Single + 1 Sofa Bed',
          '1 Double + 1 Sofa Bed',
          'Custom Configuration'
        ]
      },
      {
        key: 'min_occupancy',
        label: 'Minimum Occupancy',
        type: 'number',
        required: true,
        validation: { min: 1, max: 20 },
        description: 'Minimum number of guests this room can accommodate'
      },
      {
        key: 'max_occupancy',
        label: 'Maximum Occupancy', 
        type: 'number',
        required: true,
        validation: { min: 1, max: 20 },
        description: 'Maximum number of guests this room can accommodate'
      },
      {
        key: 'room_size_sqm',
        label: 'Room Size (sqm)',
        type: 'number',
        validation: { min: 1, max: 1000 },
        description: 'Room area in square meters'
      },
      
      // Location & Views
      {
        key: 'view_type',
        label: 'View Type',
        type: 'select',
        options: [
          'Garden View',
          'Sea View',
          'Ocean View',
          'City View',
          'Pool View',
          'Mountain View',
          'Courtyard View',
          'Street View',
          'No View'
        ]
      },
      
      // Amenities
      {
        key: 'bathroom_type',
        label: 'Bathroom Type',
        type: 'select',
        required: true,
        options: [
          'Private En-Suite',
          'Private Bathroom',
          'Shared Bathroom',
          'Shared Facilities'
        ]
      },
      {
        key: 'room_amenities',
        label: 'Room Amenities',
        type: 'amenities',
        options: [
          'Free WiFi',
          'Air Conditioning',
          'Heating',
          'TV',
          'Minibar',
          'Safe',
          'Balcony',
          'Terrace',
          'Kitchenette',
          'Coffee Machine',
          'Tea/Coffee Making',
          'Hair Dryer',
          'Iron',
          'Ironing Board',
          'Desk',
          'Sofa',
          'Seating Area',
          'Dining Area',
          'Wardrobe',
          'Closet'
        ]
      },
      {
        key: 'accessibility_features',
        label: 'Accessibility Features',
        type: 'multiselect',
        options: [
          'Wheelchair Accessible',
          'Ground Floor Access',
          'Elevator Access',
          'Wide Doorways',
          'Accessible Bathroom',
          'Grab Bars',
          'Roll-in Shower',
          'Lowered Countertops',
          'Visual Alerts',
          'Hearing Impaired Equipment'
        ]
      },
    ]
  },
  
  activity: {
    name: 'Activity',
    description: 'Tours, excursions, and experiences',
    attributes: [
      // Core Activity Information
      {
        key: 'activity_type',
        label: 'Activity Type',
        type: 'select',
        required: true,
        options: [
          'City Tour',
          'Cultural Tour',
          'Adventure Tour',
          'Food Tour',
          'Walking Tour',
          'Boat Tour',
          'Bus Tour',
          'Private Tour',
          'Group Tour',
          'Workshop',
          'Experience',
          'Attraction Visit',
          'Hiking Tour',
          'Bike Tour',
          'Photography Tour',
          'Art Tour',
          'Historical Tour',
          'Nature Tour',
          'Wine Tour',
          'Cooking Class',
          'Language Class',
          'Craft Workshop',
          'Spa Experience',
          'Wellness Activity',
          'Sports Activity',
          'Water Activity',
          'Air Activity',
          'Land Activity'
        ]
      },
      {
        key: 'duration_hours',
        label: 'Duration (hours)',
        type: 'number',
        required: true,
        validation: { min: 0.5, max: 24 },
        description: 'How long the activity lasts'
      },
      
      // Group Size & Requirements
      {
        key: 'min_participants',
        label: 'Minimum Participants',
        type: 'number',
        validation: { min: 1, max: 100 },
        description: 'Minimum number of people needed to run the activity'
      },
      {
        key: 'max_participants',
        label: 'Maximum Participants',
        type: 'number',
        required: true,
        validation: { min: 1, max: 1000 },
        description: 'Maximum number of people that can join'
      },
      {
        key: 'age_requirements',
        label: 'Age Requirements',
        type: 'select',
        options: [
          'All Ages',
          'Adults Only (18+)',
          'Children Welcome',
          'Teenagers Only',
          'Seniors Only',
          'Family Friendly',
          'No Children Under 12',
          'No Children Under 16',
          'Adults & Teens Only'
        ]
      },
      
      // Activity Details
      {
        key: 'difficulty_level',
        label: 'Difficulty Level',
        type: 'select',
        required: true,
        options: [
          'Easy',
          'Moderate', 
          'Challenging',
          'Extreme',
          'Beginner',
          'Intermediate',
          'Advanced',
          'Expert'
        ]
      },
      {
        key: 'physical_requirements',
        label: 'Physical Requirements',
        type: 'amenities',
        options: [
          'No Physical Requirements',
          'Basic Fitness Level',
          'Good Fitness Level',
          'High Fitness Level',
          'Walking Required',
          'Hiking Required',
          'Swimming Required',
          'Climbing Required',
          'Cycling Required',
          'Standing Required',
          'Sitting Required',
          'Wheelchair Accessible',
          'Mobility Assistance Available'
        ]
      },
      
      // What's Included
      {
        key: 'includes',
        label: 'What\'s Included',
        type: 'amenities',
        options: [
          'Professional Guide',
          'Transportation',
          'Entrance Fees',
          'Lunch',
          'Dinner',
          'Snacks',
          'Drinks',
          'Equipment',
          'Safety Equipment',
          'Insurance',
          'Hotel Pickup',
          'Hotel Dropoff',
          'Photography',
          'Souvenirs',
          'Certificate',
          'Materials',
          'Refreshments',
          'WiFi',
          'Audio Guide',
          'Map/Guidebook'
        ]
      },
      
      // Location & Environment
      {
        key: 'location_type',
        label: 'Location Type',
        type: 'select',
        options: [
          'Indoor',
          'Outdoor',
          'Mixed Indoor/Outdoor',
          'Urban',
          'Rural',
          'Coastal',
          'Mountain',
          'Forest',
          'Desert',
          'Historical Site',
          'Museum',
          'Gallery',
          'Restaurant',
          'Workshop Space',
          'Studio',
          'Park',
          'Beach',
          'River',
          'Lake'
        ]
      },
      {
        key: 'weather_dependency',
        label: 'Weather Dependency',
        type: 'select',
        options: [
          'Weather Independent',
          'Good Weather Required',
          'Indoor Alternative Available',
          'Seasonal Activity',
          'Year Round',
          'Summer Only',
          'Winter Only',
          'Rain or Shine'
        ]
      }
    ]
  },
  
  transfer: {
    name: 'Transfer',
    description: 'Transportation services',
    attributes: [
      // Core Transfer Information
      {
        key: 'vehicle_type',
        label: 'Vehicle Type',
        type: 'select',
        required: true,
        options: [
          'Car',
          'Minivan',
          'Bus',
          'Luxury Car',
          'SUV',
          'Motorcycle',
          'Boat',
          'Helicopter',
          'Private Jet',
          'Limousine',
          'Van',
          'Coach',
          'Shuttle',
          'Taxi',
          'Electric Vehicle',
          'Hybrid Vehicle',
          'Convertible',
          'Wheelchair Accessible Vehicle',
          'Executive Car',
          'Vintage Car'
        ]
      },
      {
        key: 'transfer_type',
        label: 'Transfer Type',
        type: 'select',
        required: true,
        options: [
          'Airport Transfer',
          'Hotel Transfer',
          'City Transfer',
          'Intercity Transfer',
          'Private Transfer',
          'Shared Transfer',
          'Group Transfer',
          'Sightseeing Transfer',
          'Event Transfer',
          'Wedding Transfer',
          'Corporate Transfer',
          'Medical Transfer',
          'VIP Transfer',
          'Scheduled Transfer',
          'On-Demand Transfer',
          'Charter Transfer',
          'Tour Transfer'
        ]
      },
      
      // Capacity & Duration
      {
        key: 'capacity',
        label: 'Passenger Capacity',
        type: 'number',
        required: true,
        validation: { min: 1, max: 100 },
        description: 'Maximum number of passengers'
      },
      {
        key: 'duration_minutes',
        label: 'Duration (minutes)',
        type: 'number',
        validation: { min: 5, max: 1440 },
        description: 'Estimated transfer duration'
      },
      
      // Service Details
      {
        key: 'service_level',
        label: 'Service Level',
        type: 'select',
        options: [
          'Economy',
          'Standard',
          'Premium',
          'Luxury',
          'VIP',
          'Executive',
          'First Class',
          'Business Class'
        ]
      },
      {
        key: 'transfer_features',
        label: 'Transfer Features',
        type: 'amenities',
        options: [
          'Meet & Greet Service',
          'Flight Tracking',
          'Real-time Updates',
          'WiFi Available',
          'Air Conditioning',
          'Refreshments',
          'Newspapers/Magazines',
          'Child Seats Available',
          'Wheelchair Accessible',
          'Luggage Assistance',
          'Multi-language Driver',
          'Professional Driver',
          'GPS Navigation',
          'Phone Charging',
          'Bottled Water',
          'Umbrellas Available',
          'Tour Commentary',
          'Flexible Timing',
          '24/7 Availability'
        ]
      },
      
      // Pickup & Dropoff
      {
        key: 'pickup_locations',
        label: 'Pickup Locations',
        type: 'select',
        options: [
          'Airport',
          'Hotel',
          'Train Station',
          'Bus Station',
          'Port',
          'City Center',
          'Residential Address',
          'Office Building',
          'Event Venue',
          'Custom Location',
          'Multiple Locations',
          'Any Location in City',
          'Specific Area Only'
        ]
      },
      {
        key: 'dropoff_locations',
        label: 'Dropoff Locations',
        type: 'select',
        options: [
          'Airport',
          'Hotel',
          'Train Station',
          'Bus Station',
          'Port',
          'City Center',
          'Residential Address',
          'Office Building',
          'Event Venue',
          'Custom Location',
          'Multiple Locations',
          'Any Location in City',
          'Specific Area Only'
        ]
      },
      
      // Booking & Availability
      {
        key: 'booking_type',
        label: 'Booking Type',
        type: 'select',
        options: [
          'Instant Booking',
          'Advance Booking Required',
          'Same Day Booking',
          'Flexible Booking',
          'Recurring Booking',
          'One-time Booking',
          'Group Booking Only',
          'Individual Booking Only'
        ]
      },
      {
        key: 'availability_hours',
        label: 'Availability Hours',
        type: 'select',
        options: [
          '24/7',
          'Business Hours Only',
          'Daytime Only',
          'Evening Only',
          'Weekend Only',
          'Weekday Only',
          'Peak Hours Only',
          'Off-Peak Hours Only',
          'Custom Hours'
        ]
      }
    ]
  },
  
  event: {
    name: 'Event',
    description: 'Concerts, shows, sports events, and special occasions',
    attributes: [
      // Core Event Information
      {
        key: 'event_type',
        label: 'Event Type',
        type: 'select',
        required: true,
        options: [
          'Concert',
          'Sports Event',
          'Theater Show',
          'Conference',
          'Exhibition',
          'Festival',
          'Wedding',
          'Corporate Event',
          'Private Party',
          'Cultural Event',
          'Comedy Show',
          'Dance Performance',
          'Opera',
          'Musical',
          'Circus',
          'Magic Show',
          'Stand-up Comedy',
          'Art Exhibition',
          'Food Festival',
          'Wine Tasting'
        ]
      },
      {
        key: 'seating_category',
        label: 'Seating Category',
        type: 'select',
        required: true,
        options: [
          'VIP',
          'Premium',
          'Standard',
          'General Admission',
          'Standing',
          'Balcony',
          'Box Seats',
          'Floor Seats',
          'Front Row',
          'Back Row',
          'Side View',
          'Restricted View',
          'Wheelchair Accessible',
          'Student/Child',
          'Senior Citizen'
        ]
      },
      
      
      // Event Details
      {
        key: 'age_restriction',
        label: 'Age Restriction',
        type: 'select',
        options: [
          'All Ages',
          '18+',
          '21+',
          'Family Friendly',
          'Adults Only',
          'Children Welcome',
          'No Children',
          'Teenagers Only'
        ]
      },
      {
        key: 'event_features',
        label: 'Event Features',
        type: 'amenities',
        options: [
          'Live Music',
          'DJ',
          'Dancing',
          'Food Available',
          'Bar Service',
          'VIP Lounge',
          'Backstage Access',
          'Meet & Greet',
          'Photo Opportunities',
          'Merchandise Stand',
          'Parking Available',
          'Public Transport Access',
          'Wheelchair Accessible',
          'Indoor Event',
          'Outdoor Event',
          'Covered Seating',
          'Standing Room Only',
          'Seated Event',
          'Interactive',
          'Educational'
        ]
      },
      
      // Ticketing & Access
      {
        key: 'ticket_type',
        label: 'Ticket Type',
        type: 'select',
        required: true,
        options: [
          'Single Entry',
          'Multi-Day Pass',
          'Season Pass',
          'Membership',
          'Day Pass',
          'Weekend Pass',
          'VIP Package',
          'Group Ticket',
          'Student Ticket',
          'Senior Ticket',
          'Child Ticket',
          'Family Package'
        ]
      },
      {
        key: 'entry_method',
        label: 'Entry Method',
        type: 'select',
        options: [
          'Digital Ticket',
          'Physical Ticket',
          'QR Code',
          'RFID Wristband',
          'Paper Ticket',
          'Mobile App',
          'Email Confirmation',
          'Will Call',
          'Print at Home',
          'Digital Wallet'
        ]
      },
      
      // Restrictions & Policies
      {
        key: 'restrictions',
        label: 'Event Restrictions',
        type: 'amenities',
        options: [
          'No Photography',
          'No Video Recording',
          'No Food/Drink',
          'No Smoking',
          'No Pets',
          'No Backpacks',
          'No Large Bags',
          'No Cameras',
          'No Outside Food',
          'No Alcohol',
          'No Weapons',
          'No Professional Equipment',
          'Age Verification Required',
          'ID Required',
          'Dress Code Enforced',
          'Security Check Required'
        ]
      }
    ]
  },
  
  meal: {
    name: 'Meal',
    description: 'Restaurants, dining experiences, and food services',
    attributes: [
      {
        key: 'meal_type',
        label: 'Meal Type',
        type: 'select',
        required: true,
        options: [
          'Breakfast',
          'Lunch',
          'Dinner',
          'Brunch',
          'Afternoon Tea',
          'High Tea',
          'Snacks',
          'Full Board',
          'Half Board',
          'Bed & Breakfast',
          'Beverages Only',
          'Coffee & Pastries',
          'Late Night'
        ]
      },
      {
        key: 'cuisine_type',
        label: 'Cuisine Type',
        type: 'select',
        required: true,
        options: [
          'Local',
          'International',
          'Italian',
          'French',
          'Asian',
          'Mediterranean',
          'Seafood',
          'Vegetarian',
          'Vegan',
          'Fusion',
          'Japanese',
          'Thai',
          'Chinese',
          'Indian',
          'Mexican',
          'American',
          'Middle Eastern',
          'African',
          'European'
        ]
      },
      {
        key: 'dining_style',
        label: 'Dining Style',
        type: 'select',
        required: true,
        options: [
          'Buffet',
          'A la Carte',
          'Set Menu',
          'Fine Dining',
          'Casual Dining',
          'Street Food',
          'Food Tour',
          'Cooking Class',
          'Tapas',
          'Degustation',
          'Family Style',
          'Plated Service',
          'Self Service'
        ]
      },
      {
        key: 'dietary_options',
        label: 'Dietary Options',
        type: 'amenities',
        options: [
          'Vegetarian',
          'Vegan',
          'Gluten Free',
          'Halal',
          'Kosher',
          'Dairy Free',
          'Nut Free',
          'Low Sodium',
          'Keto',
          'Paleo',
          'Raw Food',
          'Organic',
          'Local Ingredients'
        ]
      },
      {
        key: 'service_features',
        label: 'Service Features',
        type: 'amenities',
        options: [
          'Live Music',
          'Entertainment',
          'Outdoor Seating',
          'Private Room',
          'Wine Pairing',
          'Chef Table',
          'Cooking Demonstration',
          'Sommelier Service',
          'Valet Parking',
          'WiFi Available',
          'Child Friendly',
          'Romantic Setting',
          'Business Meeting Space',
          'Group Dining',
          'Takeaway Available',
          'Delivery Available'
        ]
      },
      {
        key: 'capacity',
        label: 'Maximum Capacity',
        type: 'number',
        required: true,
        validation: { min: 1, max: 1000 },
        description: 'Maximum number of guests'
      },
      {
        key: 'duration_minutes',
        label: 'Duration (minutes)',
        type: 'number',
        validation: { min: 15, max: 300 },
        description: 'Typical dining duration'
      },
      {
        key: 'price_per_person',
        label: 'Price per Person',
        type: 'number',
        required: true,
        validation: { min: 0 },
        description: 'Base price per person'
      },
      {
        key: 'dress_code',
        label: 'Dress Code',
        type: 'select',
        options: [
          'Casual',
          'Smart Casual',
          'Business Casual',
          'Formal',
          'Black Tie',
          'No Dress Code'
        ]
      },
      {
        key: 'age_restrictions',
        label: 'Age Restrictions',
        type: 'select',
        options: [
          'All Ages',
          '18+ Only',
          '21+ Only',
          'Family Friendly',
          'Adults Only'
        ]
      },
      {
        key: 'booking_requirements',
        label: 'Booking Requirements',
        type: 'amenities',
        options: [
          'Advance Booking Required',
          'Deposit Required',
          'Group Minimum',
          'Special Dietary Requests',
          'Confirmation Required',
          'Cancellation Policy',
          'No Booking Required',
          'Walk-ins Welcome'
        ]
      }
    ]
  },
  
  equipment: {
    name: 'Equipment',
    description: 'Rental equipment, gear, and tools',
    attributes: [
      {
        key: 'equipment_type',
        label: 'Equipment Type',
        type: 'select',
        required: true,
        options: [
          'Sports Equipment',
          'Outdoor Gear',
          'Electronics',
          'Transportation',
          'Photography',
          'Audio/Visual',
          'Safety Equipment',
          'Tools',
          'Furniture',
          'Water Sports',
          'Winter Sports',
          'Adventure Gear',
          'Camping Equipment',
          'Fitness Equipment',
          'Musical Instruments',
          'Event Equipment',
          'Medical Equipment',
          'Industrial Equipment'
        ]
      },
      {
        key: 'rental_duration',
        label: 'Rental Duration',
        type: 'select',
        required: true,
        options: [
          'Hourly',
          'Daily',
          'Weekly',
          'Monthly',
          'Event Duration',
          'Seasonal',
          'Annual',
          'Flexible'
        ]
      },
      {
        key: 'equipment_features',
        label: 'Equipment Features',
        type: 'amenities',
        options: [
          'Waterproof',
          'Shockproof',
          'Lightweight',
          'Portable',
          'Professional Grade',
          'Beginner Friendly',
          'Advanced Level',
          'Weather Resistant',
          'UV Protected',
          'Anti-Theft',
          'GPS Enabled',
          'Wireless',
          'Bluetooth Compatible',
          'Battery Powered',
          'Solar Powered',
          'Manual Operation',
          'Automatic',
          'Adjustable',
          'Foldable',
          'Modular',
          'Maintenance Included',
          'Insurance Included',
          'Delivery Available',
          'Pickup Service',
          'Training Provided',
          'Technical Support',
          'Warranty Included'
        ]
      },
      {
        key: 'condition',
        label: 'Equipment Condition',
        type: 'select',
        required: true,
        options: [
          'Brand New',
          'Excellent',
          'Good',
          'Fair',
          'Refurbished',
          'Vintage',
          'Collector Item'
        ]
      },
      {
        key: 'capacity',
        label: 'Capacity/Size',
        type: 'select',
        options: [
          'Single Person',
          '2-4 People',
          '5-10 People',
          '10-20 People',
          '20+ People',
          'Small (Under 5kg)',
          'Medium (5-15kg)',
          'Large (15-30kg)',
          'Extra Large (30kg+)',
          'Custom Size'
        ]
      },
      {
        key: 'age_restrictions',
        label: 'Age Restrictions',
        type: 'select',
        options: [
          'All Ages',
          '12+ Years',
          '16+ Years',
          '18+ Years',
          '21+ Years',
          'Adults Only',
          'Children with Adult',
          'No Age Limit'
        ]
      },
      {
        key: 'skill_level',
        label: 'Required Skill Level',
        type: 'select',
        options: [
          'Beginner',
          'Intermediate',
          'Advanced',
          'Expert',
          'Professional',
          'Any Level',
          'Training Required',
          'Certification Required'
        ]
      },
      {
        key: 'safety_requirements',
        label: 'Safety Requirements',
        type: 'amenities',
        options: [
          'Safety Briefing Required',
          'Helmet Required',
          'Safety Harness',
          'Life Jacket Required',
          'Protective Gear',
          'First Aid Kit',
          'Emergency Contact',
          'Insurance Required',
          'Waiver Required',
          'Supervision Required',
          'Group Size Limit',
          'Weather Dependent',
          'Medical Clearance',
          'Experience Verification',
          'Age Verification'
        ]
      },
      {
        key: 'delivery_options',
        label: 'Delivery Options',
        type: 'amenities',
        options: [
          'Pickup Only',
          'Local Delivery',
          'Nationwide Delivery',
          'International Shipping',
          'Same Day Delivery',
          'Next Day Delivery',
          'Scheduled Delivery',
          'White Glove Service',
          'Assembly Included',
          'Setup Service',
          'Training Included',
          'Collection Service'
        ]
      },
      {
        key: 'maintenance_support',
        label: 'Maintenance & Support',
        type: 'amenities',
        options: [
          'Maintenance Included',
          'Repair Service',
          'Replacement Available',
          'Technical Support',
          'User Manual',
          'Video Tutorials',
          'Phone Support',
          'Email Support',
          'Live Chat',
          'On-Site Support',
          'Remote Support',
          'Warranty Service',
          'Upgrade Options',
          'Training Sessions'
        ]
      },
      {
        key: 'rental_price_per_day',
        label: 'Rental Price per Day',
        type: 'number',
        required: true,
        validation: { min: 0 },
        description: 'Base daily rental price'
      },
      {
        key: 'deposit_required',
        label: 'Deposit Required',
        type: 'number',
        validation: { min: 0 },
        description: 'Security deposit amount'
      },
      {
        key: 'minimum_rental_days',
        label: 'Minimum Rental Days',
        type: 'number',
        validation: { min: 1 },
        description: 'Minimum rental period'
      }
    ]
  },
  
  pass: {
    name: 'Pass',
    description: 'Access passes, memberships, and entry tickets',
    attributes: [
      {
        key: 'pass_type',
        label: 'Pass Type',
        type: 'select',
        required: true,
        options: [
          'Museum Pass',
          'City Pass',
          'Transport Pass',
          'Theme Park Pass',
          'Ski Pass',
          'Gym Membership',
          'Club Membership',
          'VIP Access',
          'Priority Pass',
          'Concert Pass',
          'Festival Pass',
          'Sports Pass',
          'Cultural Pass',
          'Adventure Pass',
          'Wellness Pass',
          'Food Pass',
          'Shopping Pass',
          'Entertainment Pass',
          'Educational Pass',
          'Family Pass',
          'Student Pass',
          'Senior Pass',
          'Group Pass',
          'Annual Pass',
          'Season Pass',
          'Multi-Day Pass',
          'Single Entry Pass'
        ]
      },
      {
        key: 'validity_days',
        label: 'Validity (days)',
        type: 'number',
        required: true,
        validation: { min: 1, max: 365 },
        description: 'Number of days the pass is valid'
      },
      {
        key: 'includes_access',
        label: 'Includes Access To',
        type: 'amenities',
        options: [
          'Multiple Attractions',
          'Public Transport',
          'Museums',
          'Restaurants',
          'Shops',
          'Priority Entry',
          'Skip the Line',
          'Guided Tours',
          'Audio Guides',
          'Special Exhibitions',
          'Behind the Scenes',
          'VIP Areas',
          'Lounge Access',
          'Complimentary Services',
          'Discounts',
          'Free Parking',
          'WiFi Access',
          'Concierge Service',
          'Photo Opportunities',
          'Souvenir Shop',
          'Food & Beverage',
          'Entertainment',
          'Workshops',
          'Classes',
          'Events',
          'Networking',
          'Spa Services',
          'Fitness Facilities',
          'Swimming Pool',
          'Tennis Court',
          'Golf Course',
          'Beach Access',
          'Mountain Access',
          'Ski Lifts',
          'Equipment Rental',
          'Lessons',
          'Tours',
          'Activities'
        ]
      },
      {
        key: 'pass_benefits',
        label: 'Pass Benefits',
        type: 'amenities',
        options: [
          'Unlimited Entry',
          'Priority Booking',
          'Fast Track Entry',
          'Skip the Queue',
          'VIP Treatment',
          'Exclusive Access',
          'Member Discounts',
          'Complimentary Services',
          'Free Parking',
          'WiFi Access',
          'Concierge Service',
          'Photo Opportunities',
          'Souvenir Shop Access',
          'Food & Beverage Credits',
          'Entertainment Access',
          'Workshop Participation',
          'Class Enrollment',
          'Event Invitations',
          'Networking Opportunities',
          'Spa Access',
          'Fitness Facilities',
          'Swimming Pool',
          'Tennis Court',
          'Golf Course',
          'Beach Access',
          'Mountain Access',
          'Ski Lifts',
          'Equipment Rental',
          'Lessons Included',
          'Tour Participation',
          'Activity Access',
          'Transportation',
          'Accommodation Discounts',
          'Dining Discounts',
          'Shopping Discounts',
          'Partner Benefits',
          'Loyalty Points',
          'Upgrade Options',
          'Transferable',
          'Refundable',
          'Extendable'
        ]
      },
      {
        key: 'age_restrictions',
        label: 'Age Restrictions',
        type: 'select',
        options: [
          'All Ages',
          'Children (Under 12)',
          'Teenagers (13-17)',
          'Adults (18+)',
          'Seniors (65+)',
          'Students Only',
          'Family Pass Required',
          'No Age Limit'
        ]
      },
      {
        key: 'usage_restrictions',
        label: 'Usage Restrictions',
        type: 'amenities',
        options: [
          'Peak Hours Excluded',
          'Weekend Restrictions',
          'Holiday Exclusions',
          'Blackout Dates',
          'Advance Booking Required',
          'Same Day Booking Only',
          'Group Size Limits',
          'Time Slot Restrictions',
          'Weather Dependent',
          'Capacity Limits',
          'Member Only',
          'Guest Restrictions',
          'Transfer Restrictions',
          'Refund Restrictions',
          'Extension Fees',
          'Upgrade Fees',
          'Cancellation Policy',
          'No Show Policy',
          'Late Arrival Policy',
          'Dress Code Required',
          'ID Verification',
          'Age Verification',
          'Student ID Required',
          'Membership Required',
          'Insurance Required',
          'Waiver Required'
        ]
      },
      {
        key: 'pass_features',
        label: 'Pass Features',
        type: 'amenities',
        options: [
          'Digital Pass',
          'Physical Card',
          'Mobile App',
          'QR Code',
          'RFID Technology',
          'Biometric Access',
          'Photo ID',
          'Barcode',
          'NFC Enabled',
          'Offline Access',
          'Online Booking',
          'Real-time Updates',
          'Push Notifications',
          'Location Services',
          'GPS Tracking',
          'Social Sharing',
          'Photo Gallery',
          'Review System',
          'Rating System',
          'Recommendations',
          'Personalization',
          'History Tracking',
          'Analytics',
          'Reporting',
          'Customer Support',
          'Live Chat',
          'Phone Support',
          'Email Support',
          'FAQ Section',
          'User Guide',
          'Video Tutorials',
          'Help Center',
          'Community Forum',
          'Feedback System',
          'Suggestion Box',
          'Complaint System',
          'Refund System',
          'Upgrade System',
          'Renewal System',
          'Expiry Alerts',
          'Reminder Notifications'
        ]
      },
      {
        key: 'pass_price',
        label: 'Pass Price',
        type: 'number',
        required: true,
        validation: { min: 0 },
        description: 'Base price for the pass'
      },
      {
        key: 'discount_available',
        label: 'Discount Available',
        type: 'toggle',
        required: false
      },
      {
        key: 'group_discount',
        label: 'Group Discount (%)',
        type: 'number',
        validation: { min: 0, max: 100 },
        description: 'Percentage discount for group bookings'
      },
      {
        key: 'early_bird_discount',
        label: 'Early Bird Discount (%)',
        type: 'number',
        validation: { min: 0, max: 100 },
        description: 'Percentage discount for early bookings'
      },
      {
        key: 'refund_policy',
        label: 'Refund Policy',
        type: 'select',
        options: [
          'No Refunds',
          'Full Refund (24h)',
          'Full Refund (48h)',
          'Full Refund (7 days)',
          'Partial Refund',
          'Credit Only',
          'Exchange Only',
          'Case by Case',
          'Weather Dependent',
          'Force Majeure'
        ]
      }
    ]
  },
  
  ancillary: {
    name: 'Ancillary',
    description: 'Additional services, add-ons, and supplementary products',
    attributes: [
      {
        key: 'service_type',
        label: 'Service Type',
        type: 'select',
        required: true,
        options: [
          'Insurance',
          'Travel Documents',
          'Concierge Service',
          'Photography',
          'Translation',
          'Child Care',
          'Pet Care',
          'Luggage Service',
          'Priority Service',
          'VIP Service',
          'Airport Services',
          'Hotel Services',
          'Transportation Services',
          'Entertainment Services',
          'Wellness Services',
          'Business Services',
          'Personal Services',
          'Emergency Services',
          'Communication Services',
          'Financial Services',
          'Legal Services',
          'Medical Services',
          'Security Services',
          'Cleaning Services',
          'Maintenance Services',
          'Technical Services',
          'Consulting Services',
          'Training Services',
          'Event Services',
          'Catering Services',
          'Audio/Visual Services',
          'Photography Services',
          'Videography Services',
          'Gift Services',
          'Souvenir Services',
          'Memory Services',
          'Experience Services',
          'Cultural Services',
          'Educational Services',
          'Recreational Services',
          'Sports Services',
          'Fitness Services',
          'Beauty Services',
          'Spa Services',
          'Massage Services',
          'Therapy Services',
          'Coaching Services',
          'Language Services',
          'Interpretation Services',
          'Guiding Services',
          'Tour Services',
          'Excursion Services'
        ]
      },
      {
        key: 'delivery_method',
        label: 'Delivery Method',
        type: 'select',
        required: true,
        options: [
          'Digital',
          'Physical',
          'In-Person Service',
          'Remote Service',
          'On-Site Service',
          'Mobile Service',
          'Home Service',
          'Office Service',
          'Hotel Service',
          'Airport Service',
          'Venue Service',
          'Event Service',
          'Tour Service',
          'Excursion Service'
        ]
      },
      {
        key: 'service_features',
        label: 'Service Features',
        type: 'amenities',
        options: [
          '24/7 Available',
          'Emergency Service',
          'Priority Service',
          'VIP Service',
          'Express Service',
          'Same Day Service',
          'Next Day Service',
          'Scheduled Service',
          'Flexible Timing',
          'Customizable',
          'Personalized',
          'Professional',
          'Experienced',
          'Certified',
          'Licensed',
          'Insured',
          'Background Checked',
          'Verified',
          'Trusted',
          'Reliable',
          'Dependable',
          'Punctual',
          'Efficient',
          'Fast',
          'Quick',
          'Immediate',
          'Real-time',
          'Interactive',
          'Engaging',
          'Educational',
          'Informative',
          'Helpful',
          'Supportive',
          'Caring',
          'Friendly',
          'Courteous',
          'Professional',
          'Discrete',
          'Confidential',
          'Private',
          'Secure',
          'Safe',
          'Monitored',
          'Supervised',
          'Guided',
          'Assisted',
          'Supported',
          'Maintained',
          'Quality Assured',
          'Satisfaction Guaranteed',
          'Money Back Guarantee',
          'Value for Money',
          'Cost Effective',
          'Affordable',
          'Premium',
          'Luxury',
          'High-end',
          'Exclusive',
          'Limited',
          'Special',
          'Unique',
          'Custom',
          'Tailored',
          'Bespoke'
        ]
      },
      {
        key: 'service_duration',
        label: 'Service Duration',
        type: 'select',
        options: [
          'Instant',
          'Minutes',
          'Hours',
          'Days',
          'Weeks',
          'Months',
          'Years',
          'Ongoing',
          'Continuous',
          'Regular',
          'Periodic',
          'Seasonal',
          'Annual',
          'Monthly',
          'Weekly',
          'Daily',
          'Hourly',
          'Per Use',
          'Per Person',
          'Per Group',
          'Per Event',
          'One-time',
          'Recurring',
          'Subscription',
          'Membership'
        ]
      },
      {
        key: 'service_price',
        label: 'Service Price',
        type: 'number',
        required: true,
        validation: { min: 0 },
        description: 'Base price for the service'
      },
      {
        key: 'availability',
        label: 'Availability',
        type: 'select',
        options: [
          '24/7',
          'Business Hours',
          'Weekdays Only',
          'Weekends Only',
          'Peak Hours',
          'Off-Peak Hours',
          'Seasonal',
          'On-Demand',
          'By Appointment',
          'Limited Availability',
          'High Demand',
          'Low Demand',
          'Regular',
          'Irregular',
          'Flexible',
          'Fixed',
          'Variable',
          'Custom'
        ]
      }
    ]
  },
  
  other: {
    name: 'Other',
    description: 'Other products and services not covered by standard categories',
    attributes: [
      {
        key: 'custom_type',
        label: 'Product Type',
        type: 'text',
        required: true,
        placeholder: 'Describe the product type (e.g., "Custom Experience", "Special Service")'
      },
      {
        key: 'custom_label',
        label: 'Custom Label',
        type: 'text',
        required: false,
        placeholder: 'Optional custom label for this product'
      },
      {
        key: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Provide detailed description about this product'
      },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        required: false,
        options: [
          'Experience',
          'Service',
          'Product',
          'Add-on',
          'Upgrade',
          'Premium',
          'Special',
          'Limited Edition',
          'Seasonal',
          'Event Specific',
          'Custom',
          'Bespoke',
          'Personalized',
          'Group',
          'Individual',
          'Family',
          'Corporate',
          'Educational',
          'Recreational',
          'Cultural',
          'Adventure',
          'Wellness',
          'Entertainment',
          'Dining',
          'Transportation',
          'Accommodation',
          'Shopping',
          'Gift',
          'Souvenir',
          'Memory',
          'Photography',
          'Video',
          'Audio',
          'Digital',
          'Physical',
          'Virtual',
          'Online',
          'Offline',
          'Hybrid'
        ]
      },
      {
        key: 'target_audience',
        label: 'Target Audience',
        type: 'select',
        required: false,
        options: [
          'All Ages',
          'Adults Only',
          'Children',
          'Teenagers',
          'Seniors',
          'Families',
          'Couples',
          'Groups',
          'Individuals',
          'Students',
          'Professionals',
          'Tourists',
          'Locals',
          'International',
          'Domestic',
          'First-time Visitors',
          'Repeat Visitors',
          'VIP',
          'Budget',
          'Mid-range',
          'Luxury',
          'Adventure Seekers',
          'Culture Enthusiasts',
          'Food Lovers',
          'Nature Lovers',
          'History Buffs',
          'Art Lovers',
          'Music Lovers',
          'Sports Fans',
          'Wellness Seekers',
          'Business Travelers',
          'Leisure Travelers'
        ]
      },
      {
        key: 'duration',
        label: 'Duration',
        type: 'select',
        required: false,
        options: [
          'Instant',
          'Minutes',
          'Hours',
          'Half Day',
          'Full Day',
          'Multi-day',
          'Week',
          'Month',
          'Seasonal',
          'Annual',
          'Ongoing',
          'Flexible',
          'Custom',
          'Variable'
        ]
      },
      {
        key: 'capacity',
        label: 'Capacity',
        type: 'select',
        required: false,
        options: [
          'Individual',
          'Couple',
          'Small Group (2-4)',
          'Medium Group (5-10)',
          'Large Group (11-20)',
          'Very Large Group (21-50)',
          'Mass Group (50+)',
          'Unlimited',
          'Custom',
          'Variable'
        ]
      },
      {
        key: 'features',
        label: 'Features',
        type: 'amenities',
        options: [
          'Customizable',
          'Personalized',
          'Bespoke',
          'Unique',
          'Exclusive',
          'Limited Edition',
          'Seasonal',
          'Event Specific',
          'Group Discount',
          'Early Bird Discount',
          'Loyalty Discount',
          'Student Discount',
          'Senior Discount',
          'Family Discount',
          'Corporate Discount',
          'Bulk Discount',
          'Referral Bonus',
          'Loyalty Points',
          'Rewards Program',
          'Membership Benefits',
          'VIP Access',
          'Priority Booking',
          'Fast Track',
          'Skip the Line',
          'Exclusive Access',
          'Behind the Scenes',
          'Meet & Greet',
          'Photo Opportunities',
          'Souvenir Included',
          'Memory Book',
          'Digital Content',
          'Social Media Ready',
          'Instagram Worthy',
          'TikTok Friendly',
          'YouTube Ready',
          'Live Streaming',
          'Virtual Option',
          'Hybrid Experience',
          'Multi-language',
          'Accessibility Friendly',
          'Wheelchair Accessible',
          'Child Friendly',
          'Pet Friendly',
          'Eco-friendly',
          'Sustainable',
          'Local Sourced',
          'Artisan Made',
          'Handcrafted',
          'Traditional',
          'Modern',
          'Innovative',
          'Cutting-edge',
          'Technology Enhanced',
          'AI Powered',
          'Interactive',
          'Immersive',
          'Educational',
          'Entertaining',
          'Relaxing',
          'Adventurous',
          'Challenging',
          'Easy',
          'Beginner Friendly',
          'Advanced',
          'Expert Level',
          'Professional Grade',
          'Amateur Friendly',
          'All Skill Levels',
          'Guided',
          'Self-guided',
          'Independent',
          'Supervised',
          'Unsupervised',
          'Safe',
          'Secure',
          'Insured',
          'Licensed',
          'Certified',
          'Award Winning',
          'Highly Rated',
          'Recommended',
          'Popular',
          'Trending',
          'Viral',
          'Social Media Famous',
          'Celebrity Endorsed',
          'Expert Approved',
          'Local Favorite',
          'Hidden Gem',
          'Off the Beaten Path',
          'Secret Spot',
          'Local Secret',
          'Insider Access',
          'Exclusive Location',
          'Private Venue',
          'Public Venue',
          'Outdoor',
          'Indoor',
          'Weather Dependent',
          'All Weather',
          'Seasonal',
          'Year Round',
          'Limited Time',
          'One Time Only',
          'Recurring',
          'Regular',
          'Special Event',
          'Holiday Special',
          'Weekend Only',
          'Weekday Only',
          'Peak Season',
          'Off Season',
          'Shoulder Season',
          'Flexible Timing',
          'Fixed Schedule',
          'Custom Timing',
          'On Demand',
          'By Appointment',
          'Walk-in Welcome',
          'Advance Booking Required',
          'Same Day Booking',
          'Last Minute Available',
          'Group Bookings',
          'Private Bookings',
          'Shared Experience',
          'Solo Friendly',
          'Couple Friendly',
          'Family Friendly',
          'Group Friendly',
          'Corporate Friendly',
          'Team Building',
          'Networking',
          'Social',
          'Romantic',
          'Adventure',
          'Relaxation',
          'Education',
          'Entertainment',
          'Cultural',
          'Historical',
          'Artistic',
          'Musical',
          'Culinary',
          'Wellness',
          'Fitness',
          'Sports',
          'Nature',
          'Wildlife',
          'Photography',
          'Videography',
          'Audio Recording',
          'Live Performance',
          'Interactive',
          'Hands-on',
          'DIY',
          'Guided Tour',
          'Self-guided Tour',
          'Audio Guide',
          'Video Guide',
          'Mobile App',
          'Digital Guide',
          'Paper Guide',
          'Map Included',
          'Transportation Included',
          'Meals Included',
          'Refreshments Included',
          'Equipment Provided',
          'Materials Included',
          'Take-home Items',
          'Souvenirs',
          'Certificates',
          'Badges',
          'Trophies',
          'Prizes',
          'Gifts',
          'Memories',
          'Photos',
          'Videos',
          'Audio',
          'Digital Content',
          'Social Media Content',
          'Professional Photos',
          'Professional Videos',
          'Drone Footage',
          '360° Content',
          'VR Experience',
          'AR Experience',
          'Mixed Reality',
          'Immersive',
          'Interactive',
          'Gamified',
          'Competitive',
          'Collaborative',
          'Educational',
          'Entertaining',
          'Inspiring',
          'Motivating',
          'Relaxing',
          'Therapeutic',
          'Healing',
          'Wellness',
          'Mindfulness',
          'Meditation',
          'Yoga',
          'Fitness',
          'Sports',
          'Adventure',
          'Exploration',
          'Discovery',
          'Learning',
          'Growth',
          'Development',
          'Transformation',
          'Experience',
          'Memory',
          'Story',
          'Journey',
          'Adventure',
          'Exploration',
          'Discovery',
          'Learning',
          'Growth',
          'Development',
          'Transformation',
          'Experience',
          'Memory',
          'Story',
          'Journey'
        ]
      },
      {
        key: 'requirements',
        label: 'Requirements',
        type: 'amenities',
        options: [
          'Age Verification',
          'ID Required',
          'Passport Required',
          'Visa Required',
          'Insurance Required',
          'Medical Clearance',
          'Physical Fitness',
          'Swimming Ability',
          'Climbing Ability',
          'Hiking Experience',
          'Driving License',
          'Pilot License',
          'Diving Certification',
          'Skiing Experience',
          'Previous Experience',
          'Training Required',
          'Certification Required',
          'License Required',
          'Permit Required',
          'Authorization Required',
          'Approval Required',
          'Booking Required',
          'Advance Notice',
          'Minimum Group Size',
          'Maximum Group Size',
          'Weather Dependent',
          'Seasonal Availability',
          'Time Restrictions',
          'Dress Code',
          'Equipment Required',
          'Safety Gear',
          'Protective Equipment',
          'Special Clothing',
          'Footwear',
          'Sun Protection',
          'Weather Protection',
          'Water Protection',
          'Cold Weather Gear',
          'Hot Weather Gear',
          'Rain Gear',
          'Wind Protection',
          'UV Protection',
          'Insect Protection',
          'Allergy Considerations',
          'Dietary Restrictions',
          'Medical Conditions',
          'Mobility Requirements',
          'Accessibility Needs',
          'Language Requirements',
          'Communication Needs',
          'Technology Requirements',
          'Internet Access',
          'Mobile Device',
          'Camera',
          'Video Camera',
          'Audio Equipment',
          'Recording Equipment',
          'Transportation',
          'Accommodation',
          'Meals',
          'Refreshments',
          'Snacks',
          'Water',
          'Beverages',
          'Alcoholic Beverages',
          'Non-alcoholic Beverages',
          'Special Dietary Needs',
          'Vegetarian',
          'Vegan',
          'Gluten-free',
          'Halal',
          'Kosher',
          'Allergy-friendly',
          'Child-friendly',
          'Pet-friendly',
          'Senior-friendly',
          'Beginner-friendly',
          'Expert-level',
          'Professional-grade',
          'Amateur-friendly',
          'All skill levels',
          'Guided experience',
          'Self-guided',
          'Independent',
          'Supervised',
          'Unsupervised',
          'Safe environment',
          'Secure location',
          'Insured activity',
          'Licensed operator',
          'Certified guide',
          'Award-winning',
          'Highly rated',
          'Recommended',
          'Popular choice',
          'Trending',
          'Viral',
          'Social media famous',
          'Celebrity endorsed',
          'Expert approved',
          'Local favorite',
          'Hidden gem',
          'Off the beaten path',
          'Secret spot',
          'Local secret',
          'Insider access',
          'Exclusive location',
          'Private venue',
          'Public venue',
          'Outdoor activity',
          'Indoor activity',
          'Weather dependent',
          'All weather',
          'Seasonal',
          'Year round',
          'Limited time',
          'One time only',
          'Recurring',
          'Regular schedule',
          'Special event',
          'Holiday special',
          'Weekend only',
          'Weekday only',
          'Peak season',
          'Off season',
          'Shoulder season',
          'Flexible timing',
          'Fixed schedule',
          'Custom timing',
          'On demand',
          'By appointment',
          'Walk-in welcome',
          'Advance booking required',
          'Same day booking',
          'Last minute available',
          'Group bookings',
          'Private bookings',
          'Shared experience',
          'Solo friendly',
          'Couple friendly',
          'Family friendly',
          'Group friendly',
          'Corporate friendly',
          'Team building',
          'Networking',
          'Social',
          'Romantic',
          'Adventure',
          'Relaxation',
          'Education',
          'Entertainment',
          'Cultural',
          'Historical',
          'Artistic',
          'Musical',
          'Culinary',
          'Wellness',
          'Fitness',
          'Sports',
          'Nature',
          'Wildlife',
          'Photography',
          'Videography',
          'Audio recording',
          'Live performance',
          'Interactive',
          'Hands-on',
          'DIY',
          'Guided tour',
          'Self-guided tour',
          'Audio guide',
          'Video guide',
          'Mobile app',
          'Digital guide',
          'Paper guide',
          'Map included',
          'Transportation included',
          'Meals included',
          'Refreshments included',
          'Equipment provided',
          'Materials included',
          'Take-home items',
          'Souvenirs',
          'Certificates',
          'Badges',
          'Trophies',
          'Prizes',
          'Gifts',
          'Memories',
          'Photos',
          'Videos',
          'Audio',
          'Digital content',
          'Social media content',
          'Professional photos',
          'Professional videos',
          'Drone footage',
          '360° content',
          'VR experience',
          'AR experience',
          'Mixed reality',
          'Immersive',
          'Interactive',
          'Gamified',
          'Competitive',
          'Collaborative',
          'Educational',
          'Entertaining',
          'Inspiring',
          'Motivating',
          'Relaxing',
          'Therapeutic',
          'Healing',
          'Wellness',
          'Mindfulness',
          'Meditation',
          'Yoga',
          'Fitness',
          'Sports',
          'Adventure',
          'Exploration',
          'Discovery',
          'Learning',
          'Growth',
          'Development',
          'Transformation',
          'Experience',
          'Memory',
          'Story',
          'Journey'
        ]
      },
      {
        key: 'availability',
        label: 'Availability',
        type: 'select',
        required: false,
        options: [
          '24/7',
          'Business Hours',
          'Weekdays Only',
          'Weekends Only',
          'Peak Hours',
          'Off-Peak Hours',
          'Seasonal',
          'On-Demand',
          'By Appointment',
          'Limited Availability',
          'High Demand',
          'Low Demand',
          'Regular',
          'Irregular',
          'Flexible',
          'Fixed',
          'Variable',
          'Custom',
          'Weather Dependent',
          'Event Dependent',
          'Group Dependent',
          'Individual Only',
          'Group Only',
          'Mixed',
          'Private',
          'Public',
          'Semi-Private',
          'Exclusive',
          'Limited Edition',
          'One-time Only',
          'Recurring',
          'Annual',
          'Monthly',
          'Weekly',
          'Daily',
          'Hourly',
          'Per Request',
          'Advance Booking',
          'Same Day',
          'Last Minute',
          'Walk-in',
          'Reservation Only',
          'First Come First Served',
          'Lottery',
          'Auction',
          'Bidding',
          'Membership Required',
          'Invitation Only',
          'VIP Only',
          'Premium Only',
          'Standard Only',
          'Economy Only',
          'Budget Only',
          'Luxury Only',
          'All Levels',
          'Beginner Only',
          'Intermediate Only',
          'Advanced Only',
          'Expert Only',
          'Professional Only',
          'Amateur Only',
          'Mixed Levels',
          'All Ages',
          'Adults Only',
          'Children Only',
          'Teenagers Only',
          'Seniors Only',
          'Families Only',
          'Couples Only',
          'Groups Only',
          'Individuals Only',
          'Students Only',
          'Professionals Only',
          'Tourists Only',
          'Locals Only',
          'International Only',
          'Domestic Only',
          'First-time Visitors Only',
          'Repeat Visitors Only',
          'VIP Only',
          'Budget Only',
          'Mid-range Only',
          'Luxury Only',
          'Adventure Seekers Only',
          'Culture Enthusiasts Only',
          'Food Lovers Only',
          'Nature Lovers Only',
          'History Buffs Only',
          'Art Lovers Only',
          'Music Lovers Only',
          'Sports Fans Only',
          'Wellness Seekers Only',
          'Business Travelers Only',
          'Leisure Travelers Only',
          'Mixed Audiences',
          'All Audiences',
          'Targeted Audience',
          'Specific Audience',
          'General Audience',
          'Public Audience',
          'Private Audience',
          'Semi-Private Audience',
          'Exclusive Audience',
          'Limited Audience',
          'Unlimited Audience',
          'Open Audience',
          'Closed Audience',
          'Invited Audience',
          'Registered Audience',
          'Members Only',
          'Non-members Only',
          'Mixed Membership',
          'All Memberships',
          'No Membership Required',
          'Membership Required',
          'Premium Membership',
          'Standard Membership',
          'Basic Membership',
          'VIP Membership',
          'Gold Membership',
          'Silver Membership',
          'Bronze Membership',
          'Platinum Membership',
          'Diamond Membership',
          'Elite Membership',
          'Exclusive Membership',
          'Limited Membership',
          'Unlimited Membership',
          'Annual Membership',
          'Monthly Membership',
          'Weekly Membership',
          'Daily Membership',
          'Hourly Membership',
          'Per Use Membership',
          'One-time Membership',
          'Recurring Membership',
          'Lifetime Membership',
          'Temporary Membership',
          'Permanent Membership',
          'Flexible Membership',
          'Fixed Membership',
          'Variable Membership',
          'Custom Membership',
          'Personalized Membership',
          'Tailored Membership',
          'Bespoke Membership',
          'Made to Order Membership',
          'Handmade Membership',
          'Artisanal Membership',
          'Craft Membership',
          'Quality Membership',
          'Premium Membership',
          'Luxury Membership',
          'High-end Membership',
          'Top-tier Membership',
          'Best Membership',
          'Finest Membership',
          'Superior Membership',
          'Excellent Membership',
          'Outstanding Membership',
          'Exceptional Membership',
          'Remarkable Membership',
          'Extraordinary Membership',
          'Amazing Membership',
          'Fantastic Membership',
          'Wonderful Membership',
          'Brilliant Membership',
          'Spectacular Membership',
          'Magnificent Membership',
          'Gorgeous Membership',
          'Beautiful Membership',
          'Stunning Membership',
          'Breathtaking Membership',
          'Awe-inspiring Membership',
          'Inspiring Membership',
          'Motivating Membership',
          'Encouraging Membership',
          'Uplifting Membership',
          'Positive Membership',
          'Optimistic Membership',
          'Hopeful Membership',
          'Bright Membership',
          'Cheerful Membership',
          'Happy Membership',
          'Joyful Membership',
          'Delightful Membership',
          'Pleasant Membership',
          'Enjoyable Membership',
          'Fun Membership',
          'Entertaining Membership',
          'Amusing Membership',
          'Humorous Membership',
          'Funny Membership',
          'Comical Membership',
          'Laughable Membership',
          'Ridiculous Membership',
          'Absurd Membership',
          'Crazy Membership',
          'Wild Membership',
          'Insane Membership',
          'Intense Membership',
          'Extreme Membership',
          'Radical Membership',
          'Revolutionary Membership',
          'Groundbreaking Membership',
          'Innovative Membership',
          'Creative Membership',
          'Original Membership',
          'Unique Membership',
          'Distinctive Membership',
          'Special Membership',
          'Different Membership',
          'Alternative Membership',
          'Unconventional Membership',
          'Non-traditional Membership',
          'Modern Membership',
          'Contemporary Membership',
          'Current Membership',
          'Trendy Membership',
          'Fashionable Membership',
          'Stylish Membership',
          'Elegant Membership',
          'Sophisticated Membership',
          'Refined Membership',
          'Polished Membership',
          'Perfect Membership',
          'Flawless Membership',
          'Impeccable Membership',
          'Pristine Membership',
          'Clean Membership',
          'Fresh Membership',
          'New Membership',
          'Latest Membership',
          'Recent Membership',
          'Updated Membership',
          'Upgraded Membership',
          'Enhanced Membership',
          'Improved Membership',
          'Better Membership',
          'Superior Membership',
          'Advanced Membership',
          'Cutting-edge Membership',
          'State-of-the-art Membership',
          'High-tech Membership',
          'Digital Membership',
          'Electronic Membership',
          'Automated Membership',
          'Smart Membership',
          'Intelligent Membership',
          'AI-powered Membership',
          'Machine Learning Membership',
          'Data-driven Membership',
          'Analytics Membership',
          'Insights Membership',
          'Reporting Membership',
          'Monitoring Membership',
          'Tracking Membership',
          'Measurement Membership',
          'Evaluation Membership',
          'Assessment Membership',
          'Analysis Membership',
          'Research Membership',
          'Study Membership',
          'Investigation Membership',
          'Exploration Membership',
          'Discovery Membership',
          'Learning Membership',
          'Education Membership',
          'Training Membership',
          'Development Membership',
          'Growth Membership',
          'Progress Membership',
          'Advancement Membership',
          'Achievement Membership',
          'Success Membership',
          'Victory Membership',
          'Triumph Membership',
          'Win Membership',
          'Gain Membership',
          'Benefit Membership',
          'Advantage Membership',
          'Edge Membership',
          'Competitive Membership',
          'Superior Membership',
          'Better Membership',
          'Best Membership',
          'Top Membership',
          'Leading Membership',
          'Number One Membership',
          'First Membership',
          'Primary Membership',
          'Main Membership',
          'Core Membership',
          'Essential Membership',
          'Important Membership',
          'Critical Membership',
          'Vital Membership',
          'Necessary Membership',
          'Required Membership',
          'Mandatory Membership',
          'Compulsory Membership',
          'Obligatory Membership',
          'Essential Membership',
          'Fundamental Membership',
          'Basic Membership',
          'Elementary Membership',
          'Simple Membership',
          'Easy Membership',
          'Straightforward Membership',
          'Clear Membership',
          'Obvious Membership',
          'Apparent Membership',
          'Evident Membership',
          'Visible Membership',
          'Noticeable Membership',
          'Prominent Membership',
          'Standout Membership',
          'Remarkable Membership',
          'Notable Membership',
          'Significant Membership',
          'Important Membership',
          'Valuable Membership',
          'Precious Membership',
          'Rare Membership',
          'Scarce Membership',
          'Limited Membership',
          'Exclusive Membership',
          'Special Membership',
          'Unique Membership',
          'One-of-a-kind Membership',
          'Irreplaceable Membership',
          'Invaluable Membership',
          'Priceless Membership'
        ]
      }
    ]
  }
};

// Helper function to get attributes for a specific product type
export function getAttributesForProductType(productType: string): AttributeField[] {
  return PRODUCT_TYPE_CONFIGS[productType]?.attributes || [];
}

// Helper function to get all product types
export function getProductTypes(): string[] {
  return Object.keys(PRODUCT_TYPE_CONFIGS);
}

// Helper function to validate attribute values
export function validateAttributeValue(
  attribute: AttributeField, 
  value: any
): { isValid: boolean; error?: string } {
  if (attribute.required && (!value || value === '')) {
    return { isValid: false, error: `${attribute.label} is required` };
  }

  if (attribute.type === 'number' && value !== undefined && value !== '') {
    const numValue = Number(value);
    if (isNaN(numValue)) {
      return { isValid: false, error: `${attribute.label} must be a number` };
    }
    
    if (attribute.validation?.min !== undefined && numValue < attribute.validation.min) {
      return { isValid: false, error: `${attribute.label} must be at least ${attribute.validation.min}` };
    }
    
    if (attribute.validation?.max !== undefined && numValue > attribute.validation.max) {
      return { isValid: false, error: `${attribute.label} must be at most ${attribute.validation.max}` };
    }
  }

  if (attribute.type === 'select' && value && !attribute.options?.includes(value)) {
    return { isValid: false, error: `${attribute.label} must be one of the available options` };
  }

  if (attribute.type === 'multiselect' && value && Array.isArray(value)) {
    const invalidOptions = value.filter(v => !attribute.options?.includes(v));
    if (invalidOptions.length > 0) {
      return { isValid: false, error: `${attribute.label} contains invalid options: ${invalidOptions.join(', ')}` };
    }
  }

  return { isValid: true };
}
