-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.allocation_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_allocation_id uuid NOT NULL,
  product_option_id uuid NOT NULL,
  total_quantity integer NOT NULL,
  available_quantity integer NOT NULL,
  sold_quantity integer DEFAULT 0,
  batch_cost_per_unit numeric,
  currency character varying DEFAULT 'USD'::character varying,
  is_virtual_capacity boolean DEFAULT false,
  minimum_viable_quantity integer,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT allocation_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT allocation_inventory_contract_allocation_id_fkey FOREIGN KEY (contract_allocation_id) REFERENCES public.contract_allocations(id),
  CONSTRAINT allocation_inventory_product_option_id_fkey FOREIGN KEY (product_option_id) REFERENCES public.product_options(id)
);
CREATE TABLE public.allocation_pool_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  allocation_pool_id uuid NOT NULL,
  contract_allocation_id uuid NOT NULL,
  priority integer DEFAULT 0,
  units_used integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT allocation_pool_members_pkey PRIMARY KEY (id),
  CONSTRAINT allocation_pool_members_allocation_pool_id_fkey FOREIGN KEY (allocation_pool_id) REFERENCES public.allocation_pools(id),
  CONSTRAINT allocation_pool_members_contract_allocation_id_fkey FOREIGN KEY (contract_allocation_id) REFERENCES public.contract_allocations(id)
);
CREATE TABLE public.allocation_pools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_option_id uuid,
  pool_name character varying NOT NULL,
  pool_code character varying,
  usage_strategy character varying DEFAULT 'lowest_cost'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT allocation_pools_pkey PRIMARY KEY (id),
  CONSTRAINT allocation_pools_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT allocation_pools_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT allocation_pools_product_option_id_fkey FOREIGN KEY (product_option_id) REFERENCES public.product_options(id)
);
CREATE TABLE public.allocation_releases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_allocation_id uuid NOT NULL,
  release_date date NOT NULL,
  release_percentage numeric,
  release_quantity integer,
  penalty_applies boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT allocation_releases_pkey PRIMARY KEY (id),
  CONSTRAINT allocation_releases_contract_allocation_id_fkey FOREIGN KEY (contract_allocation_id) REFERENCES public.contract_allocations(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  action character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  ip_address inet,
  user_agent text,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  allocation_inventory_id uuid NOT NULL,
  date date NOT NULL,
  total_available integer NOT NULL,
  booked integer DEFAULT 0,
  available integer NOT NULL,
  is_closed boolean DEFAULT false,
  last_modified timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT availability_pkey PRIMARY KEY (id),
  CONSTRAINT availability_allocation_inventory_id_fkey FOREIGN KEY (allocation_inventory_id) REFERENCES public.allocation_inventory(id)
);
CREATE TABLE public.booking_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_option_id uuid,
  service_date_from date NOT NULL,
  service_date_to date,
  nights integer,
  quantity integer NOT NULL DEFAULT 1,
  adults integer DEFAULT 0,
  children integer DEFAULT 0,
  infants integer DEFAULT 0,
  contract_id uuid,
  contract_allocation_id uuid,
  allocation_inventory_id uuid,
  allocation_pool_id uuid,
  supplier_id uuid,
  supplier_reference character varying,
  unit_cost numeric,
  total_cost numeric,
  cost_currency character varying DEFAULT 'USD'::character varying,
  cost_fx_rate numeric DEFAULT 1.0,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  price_currency character varying DEFAULT 'USD'::character varying,
  price_fx_rate numeric DEFAULT 1.0,
  base_currency character varying DEFAULT 'USD'::character varying,
  unit_cost_base numeric,
  total_cost_base numeric,
  unit_price_base numeric,
  total_price_base numeric,
  quoted_at timestamp with time zone,
  quoted_unit_price numeric,
  quoted_total_price numeric,
  rate_locked boolean DEFAULT false,
  item_status USER-DEFINED DEFAULT 'provisional'::item_status,
  is_sourced boolean DEFAULT false,
  special_requests text,
  item_notes text,
  attributes jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  supplier_rate_id uuid,
  selling_rate_id uuid,
  CONSTRAINT booking_items_pkey PRIMARY KEY (id),
  CONSTRAINT booking_items_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT booking_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT booking_items_product_option_id_fkey FOREIGN KEY (product_option_id) REFERENCES public.product_options(id),
  CONSTRAINT booking_items_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT booking_items_contract_allocation_id_fkey FOREIGN KEY (contract_allocation_id) REFERENCES public.contract_allocations(id),
  CONSTRAINT booking_items_allocation_inventory_id_fkey FOREIGN KEY (allocation_inventory_id) REFERENCES public.allocation_inventory(id),
  CONSTRAINT booking_items_allocation_pool_id_fkey FOREIGN KEY (allocation_pool_id) REFERENCES public.allocation_pools(id),
  CONSTRAINT booking_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT booking_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT booking_items_supplier_rate_id_fkey FOREIGN KEY (supplier_rate_id) REFERENCES public.supplier_rates(id),
  CONSTRAINT booking_items_selling_rate_id_fkey FOREIGN KEY (selling_rate_id) REFERENCES public.selling_rates(id)
);
CREATE TABLE public.booking_passengers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  booking_item_id uuid,
  passenger_type character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  date_of_birth date,
  passport_number character varying,
  passport_expiry date,
  nationality character varying,
  email character varying,
  phone character varying,
  dietary_requirements text,
  special_requirements text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_passengers_pkey PRIMARY KEY (id),
  CONSTRAINT booking_passengers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_passengers_booking_item_id_fkey FOREIGN KEY (booking_item_id) REFERENCES public.booking_items(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  booking_reference character varying NOT NULL,
  booking_status USER-DEFINED DEFAULT 'quote'::booking_status,
  quote_reference character varying UNIQUE,
  quote_expires_at timestamp with time zone,
  quote_version integer DEFAULT 1,
  converted_from_quote_id uuid,
  customer_id uuid,
  package_id uuid,
  booking_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  confirmed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  travel_date_from date,
  travel_date_to date,
  total_cost numeric,
  total_price numeric,
  margin numeric,
  display_currency character varying DEFAULT 'USD'::character varying,
  base_currency character varying DEFAULT 'USD'::character varying,
  fx_rate_at_booking numeric DEFAULT 1.0,
  lead_passenger_name character varying,
  lead_passenger_email character varying,
  lead_passenger_phone character varying,
  total_adults integer DEFAULT 0,
  total_children integer DEFAULT 0,
  total_infants integer DEFAULT 0,
  customer_notes text,
  internal_notes text,
  payment_status character varying DEFAULT 'pending'::character varying,
  created_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bookings_converted_from_quote_id_fkey FOREIGN KEY (converted_from_quote_id) REFERENCES public.bookings(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT bookings_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT bookings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.contract_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  contract_id uuid NOT NULL,
  product_id uuid NOT NULL,
  allocation_name character varying,
  allocation_type USER-DEFINED DEFAULT 'on_request'::allocation_type,
  total_quantity integer,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  total_cost numeric,
  cost_per_unit numeric,
  currency character varying DEFAULT 'USD'::character varying,
  release_days integer,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contract_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT contract_allocations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contract_allocations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_allocations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  supplier_id uuid,
  event_id uuid,
  contract_number character varying NOT NULL,
  contract_name character varying,
  contract_type character varying DEFAULT 'on_request'::character varying,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  total_cost numeric,
  commission_rate numeric,
  payment_terms text,
  cancellation_policy text,
  terms_and_conditions text,
  contract_files jsonb DEFAULT '[]'::jsonb,
  notes text,
  status USER-DEFINED DEFAULT 'draft'::contract_status,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contracts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT contracts_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT contracts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  customer_type character varying DEFAULT 'b2c'::character varying,
  first_name character varying,
  last_name character varying,
  company_name character varying,
  email character varying,
  phone character varying,
  address jsonb,
  vip_status USER-DEFINED DEFAULT 'standard'::vip_status,
  total_bookings integer DEFAULT 0,
  total_spent numeric DEFAULT 0,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  event_name character varying NOT NULL,
  event_code character varying,
  event_type character varying,
  venue_name character varying,
  city character varying,
  country character varying,
  event_date_from date NOT NULL,
  event_date_to date NOT NULL,
  event_status character varying DEFAULT 'scheduled'::character varying,
  description text,
  event_image_url text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  from_currency character varying NOT NULL,
  to_currency character varying NOT NULL,
  rate numeric NOT NULL,
  date date NOT NULL,
  source character varying DEFAULT 'api'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organization_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  email character varying NOT NULL,
  role character varying DEFAULT 'agent'::character varying,
  token text NOT NULL UNIQUE,
  status character varying DEFAULT 'pending'::character varying,
  invited_by uuid,
  invited_by_name character varying,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT organization_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT organization_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  code character varying UNIQUE,
  email character varying,
  phone character varying,
  website character varying,
  address_line1 character varying,
  city character varying,
  country character varying,
  default_currency character varying DEFAULT 'USD'::character varying,
  base_currency character varying DEFAULT 'USD'::character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  logo_url text,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  subscription_plan character varying DEFAULT 'free'::character varying,
  subscription_status character varying DEFAULT 'active'::character varying,
  trial_ends_at timestamp with time zone,
  subscription_ends_at timestamp with time zone,
  features jsonb DEFAULT '{}'::jsonb,
  max_users integer DEFAULT 5,
  current_users integer DEFAULT 0,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  package_name character varying NOT NULL,
  package_code character varying NOT NULL,
  description text,
  duration_nights integer,
  duration_days integer,
  base_price numeric,
  currency character varying DEFAULT 'USD'::character varying,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT packages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  booking_id uuid NOT NULL,
  payment_reference character varying NOT NULL UNIQUE,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  payment_method character varying,
  payment_type character varying,
  status character varying DEFAULT 'pending'::character varying,
  due_date date,
  paid_at timestamp with time zone,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.product_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  option_name character varying NOT NULL,
  option_code character varying NOT NULL,
  description text,
  attributes jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_options_pkey PRIMARY KEY (id),
  CONSTRAINT product_options_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type_code character varying NOT NULL UNIQUE,
  type_name character varying NOT NULL,
  description text,
  icon character varying,
  is_active boolean DEFAULT true,
  CONSTRAINT product_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  product_type_id uuid NOT NULL,
  name character varying NOT NULL,
  code character varying NOT NULL,
  description text,
  location jsonb,
  venue_name character varying,
  attributes jsonb DEFAULT '{}'::jsonb,
  event_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  media jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(media) = 'array'::text),
  tags ARRAY DEFAULT '{}'::text[],
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT products_product_type_id_fkey FOREIGN KEY (product_type_id) REFERENCES public.product_types(id),
  CONSTRAINT products_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.selling_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_option_id uuid,
  rate_name character varying,
  rate_basis character varying NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  base_price numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  markup_type character varying,
  markup_amount numeric,
  pricing_details jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  target_cost numeric,
  CONSTRAINT selling_rates_pkey PRIMARY KEY (id),
  CONSTRAINT selling_rates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT selling_rates_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT selling_rates_product_option_id_fkey FOREIGN KEY (product_option_id) REFERENCES public.product_options(id)
);
CREATE TABLE public.supplier_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_option_id uuid,
  contract_id uuid,
  rate_name character varying,
  rate_basis character varying NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  base_cost numeric NOT NULL,
  currency character varying DEFAULT 'USD'::character varying,
  pricing_details jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  supplier_id uuid,
  CONSTRAINT supplier_rates_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_rates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT supplier_rates_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT supplier_rates_product_option_id_fkey FOREIGN KEY (product_option_id) REFERENCES public.product_options(id),
  CONSTRAINT supplier_rates_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT supplier_rates_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name character varying NOT NULL,
  code character varying NOT NULL,
  supplier_type character varying,
  email character varying,
  phone character varying,
  contact_info jsonb,
  address_line1 character varying,
  city character varying,
  country character varying,
  default_currency character varying DEFAULT 'USD'::character varying,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.transport_segments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_item_id uuid NOT NULL,
  segment_number integer NOT NULL,
  transport_type character varying NOT NULL,
  operator_name character varying,
  service_number character varying,
  departure_location character varying NOT NULL,
  arrival_location character varying NOT NULL,
  departure_date date NOT NULL,
  departure_time time without time zone NOT NULL,
  arrival_date date NOT NULL,
  arrival_time time without time zone NOT NULL,
  segment_details jsonb,
  booking_reference character varying,
  confirmation_status character varying DEFAULT 'pending'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transport_segments_pkey PRIMARY KEY (id),
  CONSTRAINT transport_segments_booking_item_id_fkey FOREIGN KEY (booking_item_id) REFERENCES public.booking_items(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  first_name character varying,
  last_name character varying,
  phone character varying,
  role character varying DEFAULT 'agent'::character varying,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  auth_id uuid,
  is_super_admin boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id)
);